version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
      - 8083:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    external: true
